[tox]
minversion = 1.8
basepython = python3.9
envlist = py{39}-ansible{80,70}
skipsdist = true

[testenv]
passenv = *
deps =
    -r tox-requirements.txt
    ansible80: ansible>8.0
    ansible70: ansible>=7.0

commands =
    {posargs:molecule test -s compatibility --destroy always}