---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: "46.21.245.76"

vector:
  hosts:
    vector-01:
      ansible_host: "158.160.54.5"   

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: "93.77.187.153"   
